<a href="https://colab.research.google.com/github/Duck7453/Autonomous-Project/blob/main/00PytorchQuestions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#2

import torch
random_tens = torch.rand(size = (7, 7))
random_tens


tensor([[0.6097, 0.7368, 0.0840, 0.7873, 0.1603, 0.0113, 0.0930],
        [0.3348, 0.9493, 0.4715, 0.7334, 0.1334, 0.8062, 0.9170],
        [0.0463, 0.0926, 0.5188, 0.9141, 0.8997, 0.0676, 0.4552],
        [0.2983, 0.9309, 0.0028, 0.8744, 0.9479, 0.1641, 0.2358],
        [0.2525, 0.3556, 0.1578, 0.5225, 0.2078, 0.9474, 0.8486],
        [0.9981, 0.6930, 0.1294, 0.4862, 0.2305, 0.0882, 0.5776],
        [0.3165, 0.9439, 0.0157, 0.4356, 0.6660, 0.2153, 0.9788]])

In [ ]:
#3
other = torch.rand(size = (1,7))
multiple = random_tens.mm(other.permute(1,0))
multiple

tensor([[1.1733],
        [2.2014],
        [1.4571],
        [1.8088],
        [1.7965],
        [1.9492],
        [2.1432]])

In [ ]:
#4
torch.manual_seed(0)

tensor1 = torch.rand(size=(7, 7))
tensor2 = torch.rand(size=(7, 1))
tensor3 = tensor1.mm(tensor2)
tensor3

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [ ]:
#5

torch.cuda.manual_seed(1234)

In [ ]:
#6

torch.manual_seed(1234)

device = "cuda" if torch.cuda.is_available() else "cpu"
tensor1 = torch.rand(size = (4,4)).to(device)
tensor2 = torch.rand(size = (4,4)).to(device)
tensor1
tensor2

tensor([[0.2837, 0.6567, 0.2388, 0.7313],
        [0.6012, 0.3043, 0.2548, 0.6294],
        [0.9665, 0.7399, 0.4517, 0.4757],
        [0.7842, 0.1525, 0.6662, 0.3343]])

In [ ]:
#7

tensor3 = tensor1.mm(tensor2.permute(1, 0))
tensor3

tensor([[0.6023, 0.4367, 0.6172, 0.3797],
        [0.8314, 0.5561, 0.8209, 0.3436],
        [1.0077, 1.0600, 1.5184, 1.2893],
        [1.3241, 1.2158, 1.8067, 1.1468]])

In [ ]:
#8

max = torch.max(tensor3)
min = torch.min(tensor3)
max, min

(tensor(1.8067), tensor(0.3436))

In [ ]:
#9

max = torch.argmax(tensor3)
min = torch.argmin(tensor3)
max, min

(tensor(14), tensor(7))

In [ ]:
#10

torch.manual_seed(7)
tensor1 = torch.rand(size = (1, 1, 1, 10))
tensor2 = tensor1.squeeze()
tensor1, tensor2

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]))